framework:
    cache:
        prefix_seed: 'sqrsbetting'
        default_redis_provider: '%redis_url%'
        app: cache.adapter.redis
        system: cache.adapter.redis
        pools:
            sqrsbetting_pool:
                adapter: cache.adapter.redis
                provider: sqrsbetting.redis_provider
            sqrsbetting.doctrine_pool:
                adapter: cache.adapter.redis
                provider: sqrsbetting.doctrine.redis_provider