services:
  php-fpm:
    restart: unless-stopped
    container_name: ${PROJECT}_php-fpm
    ports:
      - "80:8080"
    build:
      context: ./docker/context
      dockerfile: images/php-fpm/dev/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=sqrsbetting_php-fpm
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis

  postgres:
    restart: unless-stopped
    container_name: ${PROJECT}_postgres
    build:
      context: ./docker/context
      dockerfile: images/postgres/Dockerfile
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
      - ./docker/conf/postgres/initdb:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

  redis:
    image: "redis:alpine"
    container_name: ${PROJECT}_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - REDIS_REPLICATION_MODE=master


#  openapigen:
#    build:
#      context: ./docker/context
#      dockerfile: images/openapigen/Dockerfile
#    container_name: ${PROJECT}_openapigen
#    volumes:
#      - ./:/local

  centrifugo:
    container_name: ${PROJECT}_centrifugo
    image: centrifugo/centrifugo:latest
    ports:
      - "8000:8000"
    command: centrifugo -c centrifuge.json
    volumes:
      - "./config:/centrifugo"
