openapi: 3.0.3

info:
  title: Betting Atlas
  description: Сервис беттинга
  version: 1.0.0

servers:
  - url: http://22.22.2.2/api/v1
paths:
  /bettingapi/{wlSlug}/atlas/partner-api/v1/billing/bet:place:
    post:
      summary: Ставка
      tags:
        - Place-Bet
      parameters:
        - in: path
          name: wlSlug
          required: true
          schema:
            type: string
            example: betonred
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BetPlaceBodyRequest'
      responses:
        200:
          description: A successful response.

components:
  schemas:
    BetPlaceBodyRequest:
      type: object
      properties:
        bet:
          type: object
          properties:
            betId:
              type: string
              example: "512346"
            clientId:
              type: string
              example: "8237451"
            transactionId:
              type: string
              example: "1834"
            transactionAmount:
              type: integer
              example: 500
            betType:
              type: string
              example: "SINGLE"
            betTransactionType:
              type: string
              example: "INSTANT"
            acceptOddsChanges:
              type: string
              example: "UP"
            acceptParameterChanges:
              type: string
              example: "NO"
            odds:
              type: number
              example: 1.35
            betOdds:
              type: number
              example: 1.35
            betStatus:
              type: string
              example: "WIN"
            prematchFinCategoryName:
              type: string
              nullable: true
            prematchGameStyleCategoryName:
              type: string
              nullable: true
            liveFinCategoryName:
              type: string
              nullable: true
            liveGameStyleCategoryName:
              type: string
              nullable: true
            settleTime:
              type: integer
              example: 1636388354090
            createTime:
              type: integer
              example: 1636388350139
            updateTime:
              type: integer
              example: 1636388350155
            betMoney:
              type: object
              properties:
                currency:
                  type: string
                  example: "EUR"
                betAmount:
                  type: integer
                  example: 500
                liability:
                  type: integer
                  example: 675
                winAmount:
                  type: integer
                  example: 675
                payout:
                  type: integer
                  example: 675
              required:
                - currency
                - betAmount
                - liability
                - winAmount
                - payout
            cashOutReason:
              type: string
              example: "CASH_OUT"
            locale:
              type: string
              example: "ENG"
            betSportService:
              type: string
              example: "LIVE"
            winCombinationSize:
              type: integer
              example: 2
            outcomes:
              type: array
              nullable: true
            bonuses:
              type: array
              nullable: true
          required:
            - betId
            - clientId
            - transactionId
            - transactionAmount
            - betType
            - betTransactionType
            - acceptOddsChanges
            - acceptParameterChanges
            - odds
            - betOdds
            - betStatus
            - settleTime
            - createTime
            - updateTime
            - betMoney
            - cashOutReason
            - locale
            - betSportService
            - winCombinationSize
      required:
        - bet