FROM redis:6.0.8-alpine

### timezone ###

COPY ./docker/context/conf/redis/redis.conf /usr/local/etc/redis/redis.conf

ARG TZ="Europe/Moscow"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
